[AppSettings]
APP_VERSION = "0.0.1"
CSS_PATH = "app.css"

[InformationMessages]
NOTI_IN_DEV = "В разработке"
STEP_1 = "Шаг 1: Ввод персональных данных"
STEP_2 = "Шаг 2: Оценка"
SURNAME = "Введите Вашу фамилию"
USERNAME = "Введите Ваше имя"
USER_AFFILIATION = "Укажите Вашу принадлежность"
DROPDOWN_RATING_INFO = "Укажите Вашу оценку"
NOTI_AUTH = [
    "Заполните Ваши персональные данные",
    "Все персональные данные успешно запонены"
]
NOTI_CALCULATE_RATING = [
    "Оцените результаты объединения А и Б",
    "Оцените результат объединения А",
    "Оцените результат объединения Б",
    "Все оценки успешно выставлены"
]
DROPDOWN_KEYSKILLS = "Всего ключевых навыков - {}"
NOTI_KEYSKILLS = "Ключевые навыки не указаны"

[OtherMessages]
AUTH = "Запомнить персональные данные"
AUTH_SAVE = "Данные запомнены"
CALCULATE_RATING = "Оценить"
IMPORTANT = "Обязательно"

[Labels]
SURNAME = "Фамилия"
USERNAME = "Имя"
USER_AFFILIATION = "Принадлежность"
RESULT_A = "Результат А"
RESULT_B = "Результат Б"
DROPDOWN_RATING = "Оценка объединения по шкале от 1 до"
VACANCY_DESCRIPTION = "Описание вакансии"
DROPDOWN_KEYSKILLS = "Ключевые навыки"

[TabCreators]
"⭐ Приложение" = "app_tab"
"💡 О приложении" = "about_app_tab"
"🎭 Об авторах" = "about_authors_tab"
"📋 Зависимости" = "requirements_app_tab"

[StaticPaths]
IMAGES = "images/"
VSA = "data/vacancies_subjects_association/"
SUBJECTS = "data/subjects/"
ARENA = "data/arena/"

[Settings]
RATING_SCALE = 10
RANDOM_RESULTS = false
EVALUATE_LIMIT = 50
DROPDOWN_USER = [
    "Студент",
    "Преподаватель",
    "Представитель учебного офиса"
]

[DataframeHeaders]
RESULT = ["Дисциплины", "Уверенность"]
RU_SUBJECT = "Русскоязычное название дисциплины"